[package]
name = "nes"
version = "0.1.0"
authors = ["Michael Louis Thaler <michael.louis.thaler@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
clap = "~2.33.0"
sdl2 = "~0.32.2"

[profile.dev]
opt-level = 2  # Way too slow to run anything without optimizations
